apiVersion: v1
kind: Secret
metadata:
    name: n8n-secrets
type: Opaque
stringData:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:n3KUgx4CkiPA467gZa7o0GcLsh9kgcdlahI3OjEZnyadMOELSk5rIhkh9952Q0BE5vAH2dbn3kZv1PRopFOZ+Q==,iv:Y6eFTbw39j1ogWktEyZsBE5QUWg0MT/QIDwyGuCcnEY=,tag:lWGEZC4W7YvylDJvVAlWtg==,type:str]
    N8N_BASIC_AUTH_USER: ENC[AES256_GCM,data:Iy9Pm+M=,iv:OB+EhWkKQQM2VQCybPGZX47nOfrcjq1lLeDPByKeDHY=,tag:niLcmWXxk2yGdGdL8glIAQ==,type:str]
    N8N_BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:6+XyKLLFOm+98XibFknSfDE5YUo=,iv:UAAdxpK6O+wMWDl2bDJIxhxk9PF3UKIEDP2+n2hhNog=,tag:+kDgzOFRYhEHkDQj3JocEA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBb2JiMzN5Y3FJbUJCMmRD
            U255eXFnQ3ljRUZEUHBueE10UnJFY3pKcEFVClp1YUF6WWJzc1pKbklmWWhWMDhS
            NG5mVEd2NWsvZmU5YXRVYkpxeG4xK00KLS0tIERVdjcxZTAzbmZudmN1aklkSkNX
            RWo1UW9jRVhIWEpwcFNXV0VmTStWaFEKVN2Xv/V/soSJuw4Ksgq1Anrju3+wufSq
            AIcjLbSKt3f3toS2Mn4udRagXuChSulRO35gkRwJbfvTbUvEvqxkzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-17T15:53:17Z"
    mac: ENC[AES256_GCM,data:namhaFuvEjd9UD4xZtCaQb6THMkGuei2FTVzhgQUZGClEVJQ8jEuFhEs2FCBX9qRw5hYaaDTy2jFcRmh/ksG2uyY/BdguXCqnYwP+/aG4J99NAHBDdlGMUyxUzaLahELVkdR1GorKk+IcjMw9jmJtO4yk+aiZt8U/D2RvKv0JPQ=,iv:NTcuXvQhCxpGzX4rvNEe30mkXvGxP2pgKK0pgej2luw=,tag:vIeBkq0cbm2qv9otU+bTdQ==,type:str]
    pgp: []
    encrypted_regex: ^(N8N_ENCRYPTION_KEY|N8N_BASIC_AUTH_USER|N8N_BASIC_AUTH_PASSWORD)$
    version: 3.7.1
