apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apprise
  namespace: argocd
spec:
  project: local
  source:
    repoURL: https://github.com/nazmang/argocd-apps.git
    targetRevision: main
    path: helm-apprise
    helm:
      releaseName: apprise
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: apprise
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  info:
    - name: upstream
      value: "https://github.com/caronc/apprise-api"
