apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
spec:
  project: local
  source:
    repoURL: https://github.com/nazmang/argocd-apps.git
    targetRevision: main
    path: helm-n8n
    helm:
      releaseName: n8n
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: n8n
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  info:
    - name: upstream
      value: "https://github.com/n8n-io/n8n"
    - name: purpose
      value: "bg-coast-news automation pipeline (test deploy)"
