# {{- if .Values.manageSecrets }}
apiVersion: v1
kind: Secret
metadata:
    name: '{{ .Values.gatewayTokenSecretName }}'
type: Opaque
stringData:
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:tQZ5PMUGyzXMMwhwo+hjghK/prqXLC4ZJe3ScPh1DE1LAINKon3ivg+ZlWrzTU3Wqj0rU+g8++0M5IGQdJtWng==,iv:13aVzb98atoHsBa1tMu21PmxBJHEiNc+SweyTa0JhPA=,tag:oZaRKtLgi1nG0QHwS9wiew==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1cCsvYXRVbGVRSFkycmxS
            dkxhLytrUUxNUmptZExVY1NydUhTMFFZY21vCjhkRDVYRitQNWJRSzBBWUg2M0s1
            eXk3dzFQcndma29od1BkL0hKT3hNaTAKLS0tIHNaVENWcm55b0tnZXMvZTEvMmVn
            eVVob3FHNTgzRHpvM0JmNkFlMTcwZ28KDtJe4RYuRCPu7X8xNnXGfbmd21h0TVz5
            c+3gOwRBrZVa5IVzDayrQhXjdThRaP/GXeas2MPsCwUiIqHJsQ0GSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-10T20:21:44Z"
    mac: ENC[AES256_GCM,data:SQaILAk0Pze2C/ffktvIgm+wo2IvVY0Esg8ocigdlpOfU9dk+ghQUl80zlXEFdQc21RPX6jIPbon92yYZTQDVvFP91Wmu2kHrOc1iLuzTzVfS6oJeAwDrsA3vB/buhSNGcLkRkz4HjOHBbzp8xrVdrNbNRD/NWoXrsAjeXP0RjU=,iv:rqQSebh07O7V7kmbSe5aCboCWDHnX4oiIE2yfuY9vSQ=,tag:XsY58gbnqG7oymTCA/Ok1w==,type:str]
    pgp: []
    encrypted_regex: ^(OPENCLAW_GATEWAY_TOKEN|auth)$
    version: 3.7.1
# {{- end }}
