apiVersion: v1
kind: Secret
metadata:
    name: openclaw-gateway-token
type: Opaque
stringData:
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:/G/ykX6tplGHiuIGwNPcYkf1OrY5VbA6LcaEVtDLfxlxI0gWNfSTd30FqWX5h7fyJ0x0jpmbMHT4S5v8+pFWSA==,iv:M79rbLsbedsTcq4cO/hrdOBCsYd1FIvs/cVJGVgyW3w=,tag:Jk4PVAPHYuRmSzBYjqPIzg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzRGMvREF1Z0VWRFZaT1V3
            QTlDMWhHQWRpNkFBaHNPSUg5NHh3NFNCWGswCkN0NEs0V2lVbStIQ3R3RlBwbUtj
            QjJ3UVh6MXdSVTRTcFVxbVJySzB0ZlEKLS0tIHU5bUVFMFpKY3NyY3dyVG1haExS
            N2I1Z3RmTnQreGhUbytpMFdSdEdWQWMKHNOlctrwJyc0iM1ZRogRiqTE9WJZHG5x
            LN+6yoQEGw/ymvrLTU6D0aPTi0fCRIaYZLKkkpvfXcZbcqVv17e7xQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-10T20:50:42Z"
    mac: ENC[AES256_GCM,data:LreBH9nNsFxtjAcUvg4pU80n8CEw0M6cJ599xIA931X6ABdFkzuIA1Vo0LZEy1AcyINicj31Q4RlX/u4tK5UDCk17dEjYPfTf306ja32KRHixF2PglVsZWroNfD7ggd4nYW2mwT6LQ4PQ/86ewZ3/pyokZ+aep0ADZxivsbjn6o=,iv:CuVuVBqliZL95eDyXzbspNi7pVr07TAQdZm6HzzDk9A=,tag:89EfBr55+mntMULyLAit2Q==,type:str]
    pgp: []
    encrypted_regex: ^(OPENCLAW_GATEWAY_TOKEN|auth)$
    version: 3.7.1
