apiVersion: v1
kind: Secret
metadata:
    name: openclaw-basic-auth
type: Opaque
stringData:
    auth: ENC[AES256_GCM,data:bZzc79LqRpJ6rOPTppknRUX8ovCjTzMLLGw7KyMecdShrSPf88Ll0qlIfz9Ed0ZyHqafWzeql6iMf6tT2d27tk0tuA==,iv:NR7s2iBfzUWnqGDdlRaII0ywMdzCIGHWt1V+Nc+QNfo=,tag:SOZ+3hEb1/Bh7aapk19q4g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoWjF1MHNRaXFRZVRmZU5N
            R3AvOFNUSXkvcXZJenQ3SGdHV3Z2dDNLSUVRClgwcUs4SVllZXRRZ2ExVVVGV0tS
            NkRhTmpXVmJya3JZN0dXbnlBQTk3WTAKLS0tIFJQbXRHU0ZRcjN2YU01UE4rTFpL
            TWdPdG9QK1hOY05JVEZCOVVuY2xsa0kKXNyqzI0SUR8pMG60fs8He1zsdzhER8j4
            RuwQ7JAJ3mLvm/W2tfW6Smc9Mk3aEdHQCdYlARawGxPCAyxEk2gXTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-11T04:22:28Z"
    mac: ENC[AES256_GCM,data:TojCHS+mFj9uC9MztTFTYKRgAYUGPSO0TmpS/CAOjHIK4jZL7YnpHmYEdtERvOB2ZADqxZK16AkJhunYc5DcOo8/GqHFxvi2S69BZA+CVTuwJQCAD1WRqaJsNkb4tOTs/U6qdLDpCfm0D6HiBL2mnD8WDmJQTub1FttfxAUoKAg=,iv:kJWIA2GyOrJ3O8Unt+iNVzBCGHJwWDsxyE7mILz9nKg=,tag:fv1biQ0PW3RWVG96r6MDRw==,type:str]
    pgp: []
    encrypted_regex: ^(OPENCLAW_GATEWAY_TOKEN|auth)$
    version: 3.7.1
