apiVersion: v1
kind: Secret
metadata:
    name: health-plugin-token
type: Opaque
stringData:
    BACKEND_TOKEN: ENC[AES256_GCM,data:exb8sJapthZSHW/1EFpPciKWhbhbeCNYzDDj0gH9fdF9yTybniAdpmF263QIOpn9FK1R37Jbe003ygP2SUjGvQ==,iv:FNkF6MjiAE3qtIx+6n44rEzuRl87Qn4WkWmMe13imQ4=,tag:Q8YOAKB9V6ly3Z36tgJOZQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzSWYzakxnNTYwaVVYRDdC
            YmNvTUQvalRSb3dKdS9YQTg5YjhzbDRKakZBCkI5S2Y5R01OM3FybDVZcTNuVzFn
            VisyQzZVVW5oemNrOGowOEZRekJsK0EKLS0tIGtRQmZYZ2g3M1l4TXZtNjlnYmk1
            VVBhVWRPSHNFZGUwcGlJdWtOUlRJNVUK8jnt+eoLOIcDbWZARaK8eMOFE0NKb8X1
            qEvKBG9/DGL9sNT39Cp+CMsX/7pbgqmA4NItovaM/sEXB8wDuAUi7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-12T10:41:18Z"
    mac: ENC[AES256_GCM,data:fCViWnn+dZ32nI+rvUAMWE9zHV0j7r1VXdQqYISlCSztasy8l3BQx7w3jsbaLaqVQkTcZ4ZggQ/g/RQF5u26NC0resN43CKDN2Zb8akPYq+u69ptSv5nTtJIA/yjQOWYMV59ggLtHZ1+815+NFJO/0oNuizo5sjZHmvJOsdBNiE=,iv:u4+7TjHKJS7+vDbZ9qPun6BWWchKYbWAFVh8PZi33qY=,tag:eQp0sZJueOvyhb/nOrt5kQ==,type:str]
    pgp: []
    encrypted_regex: ^(OPENCLAW_GATEWAY_TOKEN|auth|password|BACKEND_TOKEN)$
    version: 3.7.1
