apiVersion: v1
kind: Secret
metadata:
    name: anamnestic-claw-secrets
type: Opaque
stringData:
    SQLCIPHER_KEY: ENC[AES256_GCM,data:b3NlfU8zarV642ymK3MPo+tb9qcQIpCmJK7ynMGVeYyIIScS3MLgHT44YOhfh0gbvTIDd0ugSypV0qxS3mUdiw==,iv:hnrxvxBLrqaluFHUET56j7iJlE1FCuak3AFg1ZBOV1g=,tag:/l2cQbnJzagYDkg2G0TrtA==,type:str]
    API_BEARER_TOKEN: ENC[AES256_GCM,data:8KAaf5PnC/BeW6rHpXogq3EbqbCnCyKafwa4ohUyyxWoDK/Utnl5XPpp1du3dkivkgM+PQ9YL6mnzgok2mhXyg==,iv:kD/RIL1XvFzaLD11bpIpRxkQWQ5b6eR5EsjKVXW2WBY=,tag:NRKP3kO0jBpw5bkrbqVJrA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMeGxwRWZ5YzlqZGZTWFo2
            cjJQUWVrMjZpSFJicitXOS9qZVNjQ0M4akFVCkhVMklyYWxyTVNKS2dNaDl3NGcw
            OUx4QTRwMEY4SmxuRGR6ajZWQjVlSDAKLS0tIHg2U2N4dGtyMnhvWUVwUXYzY1l6
            Y294dzAvRlUxbDVFOTlpMmdZQ2FvVU0KXTDlJefHx0Tq9bpWOOgL+O1MuY1TJb/h
            7kh3ijVqnCQABikqROIH2aL/VzallJ8bhKPdytCbkbFjWHVW/AA9UQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-11T06:20:18Z"
    mac: ENC[AES256_GCM,data:TOGCFEdFl538CE016ODSABkXDu31+ktJ12NvbVjnBUegIu4pVEdHcCqLqBTb3z1A+l5aKaD2Tcg4Axvg6TQZlgP6BluXh4VyXeVl04Z6qHuDP77dh2CvgcmSWdx1iIoOXNzjqSohX+AOSeM4oikiK4rhTVf4/eyjlkgCbM5VaUo=,iv:2RCo2Q/n30xASN63azaxO7g+EKeesZ8RrRs+HByLL3M=,tag:34hJ2NM36LoW5tetM2aFug==,type:str]
    pgp: []
    encrypted_regex: ^(SQLCIPHER_KEY|API_BEARER_TOKEN)$
    version: 3.7.1
