apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "anamnesticClaw.fullname" . }}
  labels:
    {{- include "anamnesticClaw.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  storageClassName: {{ .Values.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
