{{- if and .Values.monitoring.enabled .Values.config.enableMetrics }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "ntfy.fullname" . }}
  labels:
    {{- include "ntfy.labels" . | nindent 4 }}
    {{- with .Values.monitoring.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "ntfy.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: {{ if .Values.config.metricsListenHttp }}metrics{{ else }}http{{ end }}
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
{{- end }}
