apiVersion: v1
data:
    vault-init.yaml: ENC[AES256_GCM,data:30LDgfIrNOphuA6SRHiulPI6Qsj4XONuRCbqc/TNgib5h6SLzNqytvy4FICIQTjjdSJqqADiY8FIoEwKkb4e1jPAZnFxyGBOCKvx1/IGujXi2R1HSTiOJ0C2l4XUpyGLcG4c/VAiuHdfD3h5Q/nX2e/s6GPbf84KUu7+S6QeNrfO1ZGgrKLqed2yqGlV8YZOQpCvA8wyL0Yul/Vuzw1dcpMk4clEklp+UUpnB9f/5qmuM7oqrd8yZ5G+jlRH2XWZXmfk6efTNXVsQ9oQLkF/WVTtJ/6vfLiMbIgdl4kiCT+e3MkunthlxFQB4LFG3I45u7MO3CG4+RfgRrdyMGRsDv2N8ttD04h8J1/kle+Q94zrTBgG6YI8piTakJt8sIwDUucetCgrqqSQ4vC48txxSxk/ALUEEplKw5mqP+xaWOP0AoTXhCIiVWInbBfqxZ4wRt9homHEgR4abLiwWZ+cEq/aVfkBj8d6ij7H9OIIDDaN19k0n69d88PLGfdMXTkXZL0e1iGw7cHFMAGG5wjrTYilOTOcZ+FLtIKJ7Fh4YIAtnJMZqBaKScoAJ+uEoZeuJsRahFnm4/Zbn+JeD/mHM8Kvw+JXRx0w9yve+UcPfFDW5raFoIxmYMr2FoskvS4oIOXX9xGQ+fiv36H5f1arQNEGHYFXdKrVngI948L6CLSnfhG8ziGLJUCVQ0/YFIrsfstF2ZzjbvlN5In8COxY76MxMXScC+BD4jfdQ2SkHuY8LNLWK8SOYt3jCUF60FPjX3bq2sBh7GSer1ivAUF922qM+U4222E0+8W5plB9MmNMELn74+4xR12DdPxKLDjT1+zZRS3BLZgYQQUvPtsGu4/yralgiwxtknk2X5CQfrn6LfcxdWFYaPZEVrXLgGizc6ayiy1Qf3qoDoNWVqwl22BJ8tcXjWNkkzhGYVKUWaZM3qm0a06oQOzU62JJ5JJ5ZXRYea8FxLT3/VxwB1D9YVRW1tR4gwM1sN4MFzAXoxFlOoKkhjaedXvbv812fVaAeht50neKbCdylfyZKhQgLA+Yj4gv6g7mSoFHMvMvHUDu4cANMcoUqPZbVH9d4wzzVtrl2HIscsqhRlZOzKZ2BRIe4+QpsiiC25/53F1j7R+Ux3aLKyGBTBRIceLIQIBjlSu43G3fgPZ5k/QQ9/yHZZCBI5QjEKCmxRSkjk333B7Ulh212SPM+95uYjWZJeOuelGPFn4cgnTUax6N5L6Sp/fPCg3oOuCIA+9ds5acgCc4J+zEM810Tk4NRzu2xpHhXkJiS+tTWAeiwblYLL6nGL0w5rxEGrGcqP8WFtxHySb2EKwKDq+sRmigzLNNrJZETMwk83F2hJQA/Y3He3j23J+3eX/Wk3Gltx5QTPYthtv4wgecRMfUsq3YwQqAL/mfF656SO/WU4VgjP4vnNyrad+5ebQ=,iv:CMuU49/N587N1a7ZNORGAUmQ0fuP5gr8HAGWtgTuM64=,tag:3igq+rNdNV1fE99UpGSQdw==,type:str]
kind: Secret
metadata:
    name: vault-init
    namespace: vault
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0UEZPNldoZnBQdUNQREVE
            UWVTTGttSTMzQmw5aGl3bm50YmdKS0tTQkRZCmZYMFdVSzVRTkZNOTFPM05Walls
            N0s3Zk40UGlXTE04OStRSWlkYlVmUEkKLS0tIDFGZWJCUjlMNy9UTUtxbkRPRjVE
            S3ZRbE03ZGM0QnR1VGVOYW1nbWo0REUKKf7orL/ZIKz2VkHG3mLMonDoh2AbT+xA
            8hNqw1NZrIq+/ROQmqYP3mj4NhFdoyXXeBp58A88qN2FkC5ohOA8/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T17:20:16Z"
    mac: ENC[AES256_GCM,data:UErJ11hSDxxI2+XVzumCyHhYq7Q0pl62i4dnVqVeWXPzqqzThJYLQM1uARfh6ZZGLh3qj/8/OEaxXb+y7Hvwta5jX7p4KTbonsAOfdPm8ZV5ap/vjCt6uw4atZvCOCryig7yUm6qNs2uSKQE2QM2F8ZR31O2yI74zZvm3Bgbaoc=,iv:D3dB+hXqLaEsdKxT1ndsbB9EzjfGJbT/b8UReeLC6+U=,tag:I3S9fwen0ECUMyPK2THj+Q==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token|unseal_keys.*|vault-init.yaml|object-storage-configs.yaml|api-token|OPENSEARCH_.*)$
    version: 3.7.1
