apiVersion: v1
data:
    vault-init.yaml: ENC[AES256_GCM,data:6kOKRNS0EpqBlolfiWhkkg+pn8W0+g0GSQAmf7jAcoI5qN0Rahk4eKsM95MBR22b6SACvGMDPf8MHxO/KqEdmNRaAtand3I4uBz8lrL8F1ZPClXultV2GVet2P24qA7+GzRtDWoxF15VoVuRGvTx8jr/4RParwte70sCOkZ3CtWQ6hlerG4n67dAKta26FU4JJV13GS88UJN9IrTBQM19LCQ+3wXM7Yo1o82Qz7XvL+pxf1taFMVa90/s0nlVSu1RIUuzDcyCLr3lGmU1lXkgCHhn9/YbRdvM0UxZRE9dPy0X2EbOt1CieTKWCR9eWYOOOWoV6TEaAOyWDHVLdrf0I2Me/UIZREPRMo0zJflgVHTE+3KRbJZLdC73VCy8Ng263KUHwzVkSseopzA+56+iCfIxVBSMV69s/MY/l8TQA+eqm7JXLraq9tW3TNL7PC3nwahNuNGu8iCkQNkOimlJi7lqVdjigCYdJ38Xsq/o6yKKI8ZEJEp4M0SYBtIElNGaSiPzPeQxGL25ntvvL6AjETQlcqK9DN9YZk2Sued6TB6VddU0oQlesB15lZV7ITzcCkaQ5UsO/xedYZUfJsWC0ArfqHHWrjGVx2CzR2EBqg1Fs4xM9JBq46Xt+R85tA8oflvjza81EAw27bg2CdVNs/7crhSU3ESUe5J8V//kGKTZxV94VSLAcKY9F3Mzi0PwGWkrnapN4Vaz0z9e8VDMta63wy/+uXW5O/uBr7e8zyP/njjyTP9f0LQxhslrRoJCiAjKkBSrbNri4YkzPZsz83kSUjDry7fUbjfzr1JCFpexwF47oxG+ou9D1SMNWRoGoZTD3e/cRM3tK9DPkK9UDuQvFR/x51hL63rUEtxDJxUlB3JiBLEJDy+GHIvbEUaKu9QzgzU39v/2Pu/dCCRcaGK7eFeKLy6cNg9cF8v89EmF5imphk2whJZgBLBC7L4GqYTJZMegE4Sm62Y+yrt9ZC/VwEk4Bhy5AQWjoAjoZuEZs7CeLhRJarcAgeozTnVyGtXY1ihx60fH73cziWwn8dG4yBJTRzFZEeyXLiVvedexHXfVvJDh6+ZhU86eFXRvLB+lEAVLH2H0VnmDiNDymTkuxtYJzrjZymYg4uCAbOO/nww2DFMEFX/XzyMggiqeO/4Yup6b4TVqf8d07DBuIOe2RygPdeRLcZjR2YzGSC1oLWxJZAUGJPOksT8xZJX9Ng6BKtqUfxl42GKDFkEc4vBB6J8um4B66Bosyj3K2xVCJmAPZb+qpLcAF213ojtJ6HzkaNWja0HvJEXBRomrUemxiRrmw48mDGGQ/mTFgZA5KWd6nLGUwdMdqrTLUo+8YzprF5Npfmi7m7UcQHZpfjOo0pOObVSc9fZt0xv3gKbszIAHRu2MwHvRs5ngK6ldrdPVKmluau1tw+L6MKv8hNRyRo=,iv:YXkI4sc56c3eT+bJ4AmK3vF5SD7jIqmTNHkRd23CI0A=,tag:TYSUNXMbDxKUswEwR87xlw==,type:str]
kind: Secret
metadata:
    name: vault-init
    namespace: vault
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJV0NubkJRSys1NzZEWEZa
            c2lybG5tK2ZxS2pmLy8vTnVJQkFpVDdUWkJJCjd0UWVhR3pXdGVuS1J3ekswZ0h2
            eXplWlBxMnBFY2VpVzQwNzNBNEFmVHcKLS0tIDJPcmtDSUxMSVVyZGJ6Mll5clRV
            RmU1NnhackVSMUxhNDh4MXVqcndUQmsKTsq5NziDC5q8lJEDUn/V6WdjF223Xr8+
            +g7gNtmVen11nxhsnmNUQ286bcfZTV1FdyqIdKy+6mrUhfedR8ybww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T16:57:42Z"
    mac: ENC[AES256_GCM,data:g+Og+D062YQ0iIUnz0Xg7+MJfrDPX9gD/7Duq3zFwMjT4e3wfzDvvUmYVL+Uyg04LfLjx4FFDYcmCaLUFpmZTIPlZr2uUFsAhHmgz1gaQCZBCC+5XvGIBkxPea3tmOQXUsnWCQs47Unjp3pROnL8RoLN2QPgy2i1zDqyyU8kJfM=,iv:6EHkhlxOeUrhBM1/86XvT5d/zFK8PcexKuyAK2cjRZk=,tag:bnT3iYrZoh3y0IrJiNaY7Q==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token|unseal_keys.*|vault-init.yaml|object-storage-configs.yaml|api-token|OPENSEARCH_.*)$
    version: 3.7.1
