apiVersion: v1
data:
    vault-init.yaml: ENC[AES256_GCM,data:XaBi600XsBZX6h9Q8cQ6mifJec2TjCMUde8AnQStYamxgjp7jn0qMFfYEe3HUvHRjXTv2cacNmR9CCOTN/LEyrCCYFgSWfsZ5iNC2TdZrx9GAbt4W85IGwjG2QbeLawPs6bCrLGx4uxM19jEhS5A/qwrhemhvodECXY7z/J1I7qrHqGzN37VwdhwgzX9y5glKNdyXpNTZucI2Phm735Egddd4XIIBF/2ml5lNEm+OwEY0fMxFjIZjqqGdCXySkhVqTQIqRX8WKK5Wfn5+PwOSvjawH7UbRT/vJ/Ki4F30f2ByT5NZPLN+1oAI/KPx1s1lKU7E9aQEnzLXYEcpd7U53Ap34ir4VimDbQ/qlbevkx1MOS7tpP1OALZZnFK1op/fi//wXpYgAhzPP7wUGvSzPQ3QDHHbc2QQWq53b4XYIDwyE/KBmFoNOKfnPDPqp7bZrB1f0s/DVzHTH/LmZ23KxjS3eVLq15KH77BMrTIDee4gN16KCqVjWAAHvwS5yvo/kEeh8NCOXGIbnil1PjzZFVGMxzIobncUS7Ih7zvW89povldnJLhG1+YFZtJVhHCOtO4RrzbTkawg4fTrCPe+2TUlK2R9wZgmIdsOj/unIj1r3WEIYzoGi+BvVjkx22ZF6So3vryHZo/Gobs9/wNsOrIoU7l9G2ukeEftPdCZTxolgEmukx2vjTqp/F++p77ToLf60RaqypGgmtUujM+MhSlEtRSLCi37Q9aUWDXc6JSfHf3rxuZNvDunoZq2foKQWcQ+2S6K5Tx4gVktf/6e7naO+aW+tes9//LCf6RppaTYvLP6UjAjtUDnsHRfpqc/I7Xdj9vj0wcUIRTI34nrnIpCdPK/BX3AfUZKWaEwi1fOFXHDwLWNiSUOZ2QPILu2XcfSlxMInTYwFN8p3wDRp4CrqeCzi8Q39K/J3HYwgNa0XgsPUWvc8SfyN6ajg/ztBe0mi+vGm25rg6YziNgmw6wsYxht8Q58GVAPY7xxUWMxSODpxOTWfnBe2HcqOtJenTlwy+rbJ0nXLJx9WCTSxrEjkZFSWZVSwBC6WrrWcn76tHlQEexQy6vlhEhX+smwEfLX0UlVNdQkxcSQ13z626HBeqNzwCv+1E2i5QsPM6gxZLYFpltuC0g+9qbqyXLw0Bl4f4nY8pNBQbbbQGI/MxYMGpEgZtm3oe6tZehFVboVLgeIpE2cDC2J2O+SgLaHsp6Da+8MTcYLI+3kpPc4SCKJ/GxHceLpIEwSXi/JG07RImqABzLkrC2dF+WHgo8R1vRqz1RqfSnLFBftTRKlgi+exkpF+LQu2h8tmt5EgkGFGoTRUSELDqs0re8pr0IOi4B3vaXO/hq8KWSYz6sHtamUwL15uNVUBwuYWS3Udyhh4EkUzLchsjb44YRfZaFF8+sLAke+gDCxB8dbIPCPIZaqro=,iv:VY6cvKGtLTsDszP25xSw7/vbHwcMduQ7UD9prhl5eXA=,tag:nb3Zr0AxYkArShQYRWmk6g==,type:str]
kind: Secret
metadata:
    name: vault-init
    namespace: vault
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKUms3WDRKVDlqdjR1NUwr
            UEFFWERVNWxIL0FsZ29KbWZiZFNHK2pOZkJrClgzN0RpaEpjNDlHWmkrNkR1V2Jk
            dmFOcXB2K09iNTRxc2RuQkE2Z2Q0VWcKLS0tIFl2VjNpcm5jSS9VL05QcDdYTmFP
            NmRlUC9TVnFDVjY4NEw2cEVGcGMrSVEKpZZS4s3eaRKQZfE7kEIWxAqy707OreWU
            wNlHhns1fvPk/iFBN/5xb4BALBzDErgpcqroYm7jAQS5734IlmCPMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T15:56:37Z"
    mac: ENC[AES256_GCM,data:CvlwWldvAmShHsx/M+tTcxAWUIpxo0ghIJ2gsP7CUzeQkzrCAL/5nElCphVPycNJMzSBDYRIb7GJgC/wlpcYeTzgJtXKp+EFaYKgzrCbWIg7ZSqc6RGVE7rDgjZslg/XPCiRpiyAC5umTCr0Rr08E85ahxpw6iTC2eykjMdYKb8=,iv:zQg9S6idIMf0wvnmaQxcMuv6Nh0ELuR9v3Y+3G/lW1I=,tag:nM8VNbLtvEQEWG0m/X7NbQ==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token|unseal_keys.*|vault-init.yaml|object-storage-configs.yaml|api-token|OPENSEARCH_.*)$
    version: 3.7.1
